[font]
# Normal font style
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }  # Default for Linux/BSD: "monospace", Regular

# Bold font style
bold = { style = "Bold" }  # Inherits family from normal, Default style: Bold

# Italic font style
italic = { style = "Italic" }  # Inherits family from normal, Default style: Italic

# Bold Italic font style
bold_italic = { style = "Bold Italic" }  # Inherits family from normal, Default style: Bold Italic

# Font size in points
size = 14  # Default: 11.25

# Offset is extra space around each character
offset = { x = 0, y = 0 }  # Default: x = 0, y = 0

# Glyph offset determines the locations of the glyphs within their cells
glyph_offset = { x = 0, y = 0 }  # Default: x = 0, y = 0

# Use built-in font for box drawing characters
builtin_box_drawing = true  # Default: true

# Padding
[window]
padding = { x = 20, y = 20 }
dynamic_padding = true

# Cyberdream + Ayu Dark theme for Alacritty
[[colors.indexed_colors]]
color = "0xffbd5e"
index = 16

[[colors.indexed_colors]]
color = "0xff6e5e"
index = 17

[colors.bright]
black = "0x686868"
red = "0xF07178"
green = "0xaad94c"
yellow = "0xFFB454"
blue = "0x59C2FF"
magenta = "0xd2a6ff"
cyan = "0x95E6CB"
white = "0xFFFFFF"

[colors.normal]
black = "0x1e232b"
red = "0xea6c73"
green = "0x7fd962"
yellow = "0xf9af4f"
blue = "0x53bdfa"
magenta = "0xcda1fa"
cyan = "0x90e1c6"
white = "0xC7C7C7"

[colors.primary]
background = "0x0B0E14"
foreground = "0xBFBDB6"

[colors.selection]
background = "0x3c4048"
foreground = "0xffffff"
