# Cyberdream + Ayu Dark theme for Alacritty
[[colors.indexed_colors]]
color = "0xffbd5e"
index = 16

[[colors.indexed_colors]]
color = "0xff6e5e"
index = 17

[colors.bright]
black = "0x686868"
red = "0xF07178"
green = "0xaad94c"
yellow = "0xFFB454"
blue = "0x59C2FF"
magenta = "0xd2a6ff"
cyan = "0x95E6CB"
white = "0xFFFFFF"

[colors.normal]
black = "0x1e232b"
red = "0xea6c73"
green = "0x7fd962"
yellow = "0xf9af4f"
blue = "0x53bdfa"
magenta = "0xcda1fa"
cyan = "0x90e1c6"
white = "0xC7C7C7"

[colors.primary]
background = "0x0B0E14"
foreground = "0xBFBDB6"

[colors.selection]
background = "0x3c4048"
foreground = "0xffffff"
